USB_VID = 0x2E8A
USB_PID = 0x000B
USB_PRODUCT = "GameTiger RP2040"
USB_MANUFACTURER = "ElectroTiger"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

CIRCUITPY_KEYPAD = 1

CIRCUITPY_AUDIOIO = 1
CIRCUITPY_SDIOIO = 1

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"
